# Generated by Django 3.2.4 on 2021-06-21 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='quanitity',
            new_name='quantity',
        ),
    ]
