# Generated by Django 3.2.4 on 2021-07-15 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_rename_quanitity_card_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='img',
            field=models.URLField(default=''),
        ),
    ]
